### ISSUE TITLE
[BUG]  请实现NMTID作为环境变量写入vercel的env的功能

### ISSUE THREAD

**Issue by inoribea** [yiktllw/NeteaseCloudMusicApi#1]
## 环境
- 系统/平台: vercel

- nodejs 版本: 20

- API版本: <运行的云音乐 API 的版本号， 对应 package.json 里面的 version>

## 出现问题

复刻后deloy,无法实现二维码登录等涉及cookie的操作

## 重现步骤
复刻后deloy即可

---

![图片](https://github.com/user-attachments/assets/a2488f7b-b873-41ab-b335-d0b774400d1d)

故障端

![图片](https://github.com/user-attachments/assets/c2f895c9-4d37-4540-866a-20754cd9006f)

非故障端（您的接口）

**Comment by yiktllw** [comment]
我重新部署后，能够正常访问二维码登录
是否使用的最新版本部署？如果是，能否提供更多信息？

**Comment by inoribea** [comment]
> 我重新部署后，能够正常访问二维码登录 是否使用的最新版本部署？如果是，能否提供更多信息？

删除项目重新部署后无此问题，感谢
